### ISSUE TITLE
Feature: Skip Validation Option

### ISSUE THREAD

**Issue by MoeQuadrat** [disneystreaming/smithy-translate#216]
After some thinking over night, I'm leaning towards @Baccata's suggestion in #212—it seems like a solid move.

Issue:
When using smithy-translate, the validation step is causing issues in some scenarios. This feature request is about having the option to skip the validation during the translation process.

Solution:
Add a setting for users to skip validation during translation, aligning with @Baccata's idea of post-processing the smithy models.

**Comment by lewisjkl** [comment]
Looks like this was handled in #219. Someone tell me if I'm wrong and I will reopen the issue.
