### ISSUE TITLE
Formatter doesn't handle trailing whitespace without newline

### ISSUE THREAD

**Issue by kubukoz** [disneystreaming/smithy-translate#56]
Files that end with spaces but don't have a trailing newline aren't parsed:

```bash
printf "namespace hello\nstructure Foo {} " > in.smithy
```

```bash
cs launch com.disneystreaming.smithy:smithytranslate-cli_2.13:0.1.7 -- format in.smithy
No files were formatted

The following files were not formatted:

in.smithy
for the following reasons
unable to parse the Smithy file: in.smithy for the following reason: failed at offset 33 with error: namespace hello
structure Foo {} 
                 ^
expectation:
* must match one of the strings: {"
", "
", "//", "///"}
```

It works fine if you append a `\n` to the file, or remove the trailing space.

**Comment by daddykotex** [comment]
I think it is related to https://github.com/awslabs/smithy/issues/1522

But I was pretty sure that I had fixed that. The formatter would output an extra newline (which is annoying and to be fixed) but I was convinced I made it so that the BR in between shapes was optional after the last shape

**Comment by kubukoz** [comment]
Seems related, yeah.

I tested with 0.1.7 for sure, so it doesn't seem to be fixed (and I don't see formatting-related changes on main)
