### ISSUE TITLE
Schema not supported: {} error

### ISSUE THREAD

**Issue by keynmol** [disneystreaming/smithy-translate#95]
Quick repro:

```
cd $(mktemp -d)
coursier bootstrap --channel https://disneystreaming.github.io/coursier.json smithytranslate
git clone https://github.com/microsoft/vcpkg-tool
./bootstrap json-schema-to-smithy --input vcpkg-tool/docs/vcpkg.schema.json .
cat **/*.smithy
```

The generated schemas seem to have failed very quickly

<details>
<pre>
<code>
$version: "2.0"

namespace alloy.common

/// ISO 3166-1 Alpha-2 country code
/// Full list in https://www.iso.org/obp/ui/#search/code/
/// example: "AF", "US"
@trait(
    selector: ":test(string, member > string)"
)
structure countryCodeFormat {}

/// Email address as defined in https://www.rfc-editor.org/rfc/rfc2821 and https://www.rfc-editor.org/rfc/rfc2822
/// A more human-readable format is available here: https://www.rfc-editor.org/rfc/rfc3696#section-3
@trait(
    selector: ":test(string, member > string)"
)
structure emailFormat {}

/// A hex triplet representing a RGB color code
/// example: "#09C" (short) or "#0099CC" (full)
@trait(
    selector: ":test(string, member > string)"
)
structure hexColorCodeFormat {}

/// ISO 639-1 Alpha-2 language code or Language for short.
/// Column `ISO 639-1` in https://www.loc.gov/standards/iso639-2/php/English_list.php
/// example: "fr", "en"
@trait(
    selector: ":test(string, member > string)"
)
structure languageCodeFormat {}

/// BCP 47 Language Tag
/// IETF RFC: https://tools.ietf.org/search/bcp47
/// example: "fr-CA", "en-US"
@trait(
    selector: ":test(string, member > string)"
)
structure languageTagFormat {}
$version: "2.0"

namespace alloy.openapi

/// This traits allows the encoding of OpenAPI Extensions
/// as defined in https://swagger.io/docs/specification/openapi-extensions/.
@trait
map openapiExtensions {
    key: String
    value: Document
}
$version: "2.0"

namespace error

use smithytranslate#errorMessage

@errorMessage("Schema not supported:\n{}")
structure InputAllOf0AllOf0Item {}
$version: "2.0"

namespace vcpkg.schema

use error#InputAllOf0AllOf0Item

structure Input {}

map InputAllOf0AllOf0 {
    key: String
    value: InputAllOf0AllOf0Item
}

</code>
</pre>
</details>

**Comment by kubukoz** [comment]
also, the printing here skips the leading slash:

```
Schema not supported:
{}
Writing private/var/folders/f_/cbwjhbrs2jjg59qn23y6nhvm0000gn/T/tmp.lcgqfg6v/vcpkg/schema.smithy
Writing private/var/folders/f_/cbwjhbrs2jjg59qn23y6nhvm0000gn/T/tmp.lcgqfg6v/error.smithy
Writing private/var/folders/f_/cbwjhbrs2jjg59qn23y6nhvm0000gn/T/tmp.lcgqfg6v/alloy/common.smithy
Writing private/var/folders/f_/cbwjhbrs2jjg59qn23y6nhvm0000gn/T/tmp.lcgqfg6v/alloy/openapi.smithy
```

(the paths should start with `/private`)
